### PR TITLE
Some instructions for a beginner

### PR DESCRIPTION
**Pull request by GayanSandaruwan**

### CODE REVIEW

**Comment by overeem11** [comment]
Dear Gayan Sandaruwan,

Thank you for your files explaining how to install R packages and a dependency. Could you add some more information to "How to install the package"? I doesn't mention that this code is specific for Debian-based Linux operating systems. Please add this information.

Best regards,
Aart Overem

**Comment by giacom0rovers1** [comment]
Good morning!
I am running RAINLINK on a Fedora Linux OS machine. Fedora is not Debian-based but RPM-based like Red Hat. I can provide a file with the information needed to install the package on a system like mine too, so the user could have multiple options.

Best regards
Giacomo Roversi

**Comment by overeem11** [comment]
That would be nice. Thank you in advance!

Best regards,
Aart Overeem

Van: Giacomo Roversi [mailto:notifications@github.com]
Verzonden: vrijdag 1 juni 2018 12:05
Aan: overeem11/RAINLINK
CC: Overeem, Aart (KNMI); Comment
Onderwerp: Re: [overeem11/RAINLINK] Some instructions for a beginner (#5)


Good morning!
I am running RAINLINK on a Fedora Linux OS machine. Fedora is not Debian-based but RPM-based like Red Hat. I can provide a file with the information needed to install the package on a system like mine too, so the user could have multiple options.

Best regards
Giacomo Roversi

**Comment by GayanSandaruwan** [comment]
Hi overeem,
Thanks for the feedbacks. I'll add information to setup this in windows too.
And will format the document with markdown so a beginner can easily
understand.

**Comment by overeem11** [comment]
Thanks!

Van: GayanSandaruwan [mailto:notifications@github.com]
Verzonden: vrijdag 1 juni 2018 15:44
Aan: overeem11/RAINLINK
CC: Overeem, Aart (KNMI); Comment
Onderwerp: Re: [overeem11/RAINLINK] Some instructions for a beginner (#5)

Hi overeem,
Thanks for the feedbacks. I'll add information to setup this in windows too.
And will format the document with markdown so a beginner can easily
understand.

**Review by overeem11 — APPROVED** [review]

**Pull request merged**
